# Generated by Django 5.2.17 on 2026-10-03 10:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# Ofertas que ya mostraban las tarjetas de la tienda: (modelo, id, nombre, precio_base, % descuento)
OFERTAS = [
    ("Consolas", 2, "Nintendo", "250.00", 10),
    ("Consolas", 3, "PS4", "330.00", 30),
    ("Consolas", 5, "PS5", "529.00", 15),
    ("Juegos", 2, "Pokemon Espada", "65.00", 30),
    ("Juegos", 3, "Spider-Man 2", "75.00", 30),
    ("Accsesorios", 1, "Volante Mario Kart Pro", "170.00", 15),
    ("Accsesorios", 3, "Control", "90.00", 15),
    ("Accsesorios", 4, "Xbox Game Pass - 3 Month", "50.00", 20),
]


def cargar_ofertas(apps, schema_editor):
    from decimal import Decimal
    for modelo, pk, nombre, base, pct in OFERTAS:
        # Solo si el producto sigue existiendo con ese nombre (no pisa datos editados)
        apps.get_model("appgame", modelo).objects.filter(id=pk, nombre=nombre).update(
            precio=Decimal(base), descuento=pct
        )


class Migration(migrations.Migration):

    dependencies = [
        ("appgame", "0003_precio_decimal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accsesorios",
            name="descuento",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Porcentaje de descuento (0-90)",
                validators=[django.core.validators.MaxValueValidator(90)],
            ),
        ),
        migrations.AddField(
            model_name="consolas",
            name="descuento",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Porcentaje de descuento (0-90)",
                validators=[django.core.validators.MaxValueValidator(90)],
            ),
        ),
        migrations.AddField(
            model_name="juegos",
            name="descuento",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Porcentaje de descuento (0-90)",
                validators=[django.core.validators.MaxValueValidator(90)],
            ),
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pagado", "Pagado"),
                            ("preparacion", "En preparación"),
                            ("enviado", "Enviado"),
                            ("entregado", "Entregado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pagado",
                        max_length=12,
                    ),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                ("descuento", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("titular", models.CharField(max_length=50)),
                (
                    "marca_tarjeta",
                    models.CharField(
                        choices=[("visa", "Visa"), ("mastercard", "Mastercard")],
                        max_length=10,
                    ),
                ),
                ("ultimos4", models.CharField(max_length=4)),
                ("vencimiento", models.CharField(max_length=7)),
                ("pais", models.CharField(max_length=56)),
                ("ciudad", models.CharField(max_length=60)),
                ("calle", models.CharField(max_length=100)),
                ("casa_apto", models.CharField(max_length=20)),
                ("codigo_postal", models.CharField(max_length=10)),
                ("cod_area", models.CharField(max_length=4)),
                ("telefono", models.CharField(max_length=12)),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[("dni", "DNI"), ("pasaporte", "Pasaporte")],
                        max_length=10,
                    ),
                ),
                ("numero_documento", models.CharField(max_length=9)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "ordering": ["-creado"],
            },
        ),
        migrations.CreateModel(
            name="PedidoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=10)),
                ("producto_id", models.PositiveIntegerField()),
                ("nombre", models.CharField(max_length=160)),
                ("precio_base", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descuento", models.PositiveSmallIntegerField(default=0)),
                ("precio_final", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="appgame.pedido",
                    ),
                ),
            ],
        ),
        migrations.RunPython(cargar_ofertas, migrations.RunPython.noop),
    ]
